name: 'webqsp_simple_graphmem_test_v0.1'
model: 'simple_graphmem'
data_folder: 'datasets/webqsp/'
train_data: 'train.json'
dev_data: 'dev.json'
test_data: 'test.json'

word2id: 'vocab.txt'
relation2id: 'relations.txt'
entity2id: 'entities.txt'
word_emb_file: "word_emb_100d.npy"
entity_emb_file: "entity_emb_100d.npy"
entity_kge_file: "entity_kge_100d.npy"
relation_emb_file: "relation_emb_100d.npy"
relation_kge_file: "relation_kge_100d.npy"
freebase_id_map_file: "fbid2name.txt"

to_save_model: True
save_model_file: "model_cache/webqsp/webqsp_simple_graphmem_test_v0.1/best_model_kb"
pred_file: "model_cache/webqsp/webqsp_simple_graphmem_test_v0.1/pred_kb"
load_model_file: null

# graph options
fact_dropout: 0.0

num_layer: 1
max_query_word: 10

entity_dim: 100
word_dim: 100
kge_dim: 100
pagerank_lambda: 0.8
fact_scale: 3
use_inverse_relation: True

# optimization
num_epoch: 1000
batch_size: 10
gradient_clip: 1
learning_rate: 0.001
lstm_dropout: 0.3
linear_dropout: 0.2
is_debug: False


